include $(BASEDIR)/Makefile.base

CXXFLAGS += $(shell ${ROOTSYS}/bin/root-config --cflags)
LDFLAGS += $(shell ${ROOTSYS}/bin/root-config --libs) \
	-lGenVector -lReflex -lMathCore -lReflexDict -lboost_regex
