#------------------------------------------------------------------------------
BASEDIR ?= $(shell cd ..; pwd)
LIBFILES = BasePlot.o StandardP4Plots.o MuonPlots.o JetPlots.o \
	TrackPlots.o VertexPlots.o
PROGRAM  = libKPlots.so libKPlots.a $(LIBFILES)
#------------------------------------------------------------------------------

include $(BASEDIR)/Makefile.root
