#------------------------------------------------------------------------------
LIBFILES = BasePlot.o StandardP4Plots.o MuonPlots.o ZmumuPlots.o JetPlots.o TrackPlots.o
PROGRAM  = libKPlots.so libKPlots.a $(LIBFILES)
#------------------------------------------------------------------------------

include ../Makefile.root
