#------------------------------------------------------------------------------
LIBFILES = BaseCut.o CutFlow.o NoneCut.o PtCut.o EtaCut.o DeltaRCut.o ChargeCut.o \
	ExistenceCut.o CutGroup.o InvariantMassCut.o L1TriggerCut.o HLTriggerCut.o \
	GoodTracksFractionCut.o METoverSumEtCut.o VertexNdofCut.o BalancePhiCut.o \
	BalancePtCut.o MuonTypeCut.o IsolationCut.o EventFilterCut.o TrackQualityCut.o \
	zVertexCut.o NonFakeVertexCut.o RhoVertexCut.o UserBitFlagsCut.o MuonHLTCut.o
PROGRAM  = libKCuts.so libKCuts.a $(LIBFILES)
#------------------------------------------------------------------------------

include ../Makefile.root
