#------------------------------------------------------------------------------
PROGRAM  = libKTools.so libKTools.a
LIBFILES = FileInterface.o LumiMetadataProvider.o MinimalParser.o
#------------------------------------------------------------------------------

include ../Makefile.root
