#------------------------------------------------------------------------------
LIBFILES = FileInterface.o LumiMetadataProvider.o Directory.o EventLogger.o
PROGRAM  = libKRootTools.so libKRootTools.a $(LIBFILES)
#------------------------------------------------------------------------------

include ../Makefile.root
